#!/bin/bash

set -e

if [[ -z "$(which deno)" ]]; then
  echo "==> installing deno"
  curl -fsSL https://deno.land/x/install/install.sh | sh -s 'v1.3.3'
else
  echo "==> Deno already installed. Upgrading..."
  deno upgrade --version '1.3.3'
fi
